"""add verdict notification tracking

Revision ID: 8555f79346c0
Revises: 0004
Create Date: 2026-04-21 18:24:20.888673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8555f79346c0'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.add_column('meetings', sa.Column('proposer_notified_commit', sa.Boolean(), nullable=False))
    op.add_column('meetings', sa.Column('match_notified_commit', sa.Boolean(), nullable=False))
    op.drop_index(op.f('psychometric_identity_vector_idx'), table_name='psychometric_profiles', postgresql_ops={'identity_vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('psychometric_identity_vector_idx'), 'psychometric_profiles', ['identity_vector'], unique=False, postgresql_ops={'identity_vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('meetings', 'match_notified_commit')
    op.drop_column('meetings', 'proposer_notified_commit')
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###
